### ISSUE TITLE
Colour Scheme should be used in palette, too.

### ISSUE THREAD

**Issue by jocke-hollmann** [archimatetool/archi#1047]
Bug or feature, depending how you look at it

### Version of Archi
5.3.0

### Archi Plug-ins
No

### Operating System
MacOS 14.4.1 (23E224)

### Expected Behaviour
[archimate.zip](https://github.com/user-attachments/files/15686225/archimate.zip)
Loading/Modifying the default colour preferences should also change the colours of the symbols in the palette

### Actual Behaviour
Colours in the palette are fixed, even if the default colour for the element changed.
Changing a default colour does not result into a colour change of the symbol in the palette.

### Background
I tried to use the colour scheme from the "Mastering Archimate Edition 3.1" book, described in chapter 13.4. While I can change the colours in the setting, the changes are not reflected in the palette. As a result you pick a symbol in one colour (the fixed colour of the palette) and it is created in the default colour, defined in the settings. This is confusing.

### Experience level
I'm a total beginner with Archimate, so please forgive, if I misunderstood how this should work.

**Comment by Phillipus** [comment]
Sorry, but this is not currently possible. The icons in the palette are static PNG files, as you can see [here](https://github.com/archimatetool/archi/tree/master/com.archimatetool.editor/img/archimate). In order to achieve this, the icons would have to be generated dynamically with the given colours and that's not possible.

It is technically possible to change the fill colours of the icons programmatically (and an earlier version of Archi used to do this) but because of the anti-aliasing in the icons the result is unusable.

Thanks for your feature request but I'll close this as "unplanned" (unless one day a solution can be found).
