### ISSUE TITLE
[Feature Request] Optimise Appearance Layout

### ISSUE THREAD

**Issue by lavenderb** [archimatetool/archi#1102]
### Description

To maximise the screen area available to Views, it would be nice if the Properties Appearance Dialogue had a more efficient layout. 
I think it could be significantly reduced with a layout like the one below.

![Appearnace Proposal](https://github.com/user-attachments/assets/27ca86ff-d81f-493b-86e7-6828f2a11b64)

**Comment by Phillipus** [comment]
Hi,

it depends on where the Properties tab is placed. We used to use only single column layout and changed it to two columns. Some users complained because they have the Properties tab just under the Models Tree and had to scroll horizontally to access the other controls. So now there's an option in the Properties tab toolbar for "Single Column Layout". Because of the way the Eclipse Properties tab framework works it's quite tricky to get all controls lined up. Some controls are only visible for some selected objects and not others.

**Comment by lavenderb** [comment]
OK Phil - i can see that you've already thought about it and it's not as easy as I thought :-)
I was just being inspired to note down my wishlist by the 5.5EA release earlier today.

**Comment by lavenderb** [comment]
Consider it closed :-)
