### ISSUE TITLE
[Feature Request] Hide the Connection on a Nested Note

### ISSUE THREAD

**Issue by lavenderb** [archimatetool/archi#1103]
### Description

It's very useful to be able to indicate the status of an Element's attribute by attaching a small coloured Note.
However, unlike regular relationships, connections do not 'disappear' when a Note is nested - persisting some the visual clutter that nesting is trying to minimise.
Might it be possible to suppress the rendering of nested Connections - bringing them into line with relationship behaviour?
Failing that, could Archi provide an alternative mechanism such as the ability to set an invisible Line Style or set Opacity to 0?

**Comment by lavenderb** [comment]
Not "remove" (as in delete) as that would break the ability to link note content/appearance (e.g. colour) to properties of the attached element.
I do mean remove visually - as in "make invisible when nested".

**Comment by jbsarrodie** [comment]
> Not "remove" (as in delete) as that would break the ability to link note content/appearance (e.g. colour) to properties of the attached element.

It seems that you are using label expressions relying on connection to access linked element. You could use label expression based on (visual) parent instead.

**Comment by lavenderb** [comment]
Thanks Jean-Baptiste: 
$parent{} is what I was trying to achieve - indeed it may even be better 👍

**Comment by Phillipus** [comment]
> The code logic that handles hiding connections is designed for ArchiMate connections so it wouldn't be easy to adapt it for other connections.

Well, I spent some time investigating whether it would be possible to hide nested non-ArchiMate connections and found several issues around nested connections including some cases where a connection to connection could be left dangling in mid-air, and a few other bugs. So...this is what I changed:

- Non-ArchiMate connections can now be hidden when nested (if nesting enabled in prefs)
- Don't delete nested connection to connections, instead hide them
- This also fixes some cases where there were dangling connection to connections when nested
- Update all connected objects in the chain when nesting so that connection to connections are properly hidden

This is available in today's early access build if you want to test it.

**Comment by lavenderb** [comment]
Thanks Phil,
Sounds like a lot of work but it seems that you've solved a wider issue with nested connections.
I'll be working from home tomorrow so will give it a spin then :-)

**Comment by Phillipus** [comment]
Yes, I'm glad I looked at it. That part of the code was not nice. ;-)
