### ISSUE TITLE
[Feature request] File locking / multiuser

### ISSUE THREAD

**Issue by phavekes** [archimatetool/archi#138]
When working with a model saved on a shared location (e.g. a cifs/samba-share) there is no way knowing someone else is also editing this model. 
The last person pressing the save-button updates the file, and all edits bij the other persons are lost.

It would be great to at least know someone else has opened the file. 

It would be even better if it was possible to work on a model simultaniously, but I understand this would be hard to implement.

**Comment by jbsarrodie** [comment]
Hi,

There is no plan to support such feature but there are to ways to do similar things:
* You can have the .archimate file managed by a SVN or any other source code management system that allows you to explicitly do check-in / check-out on the model file (but don't expect to be able to merge conccurent updates, this is simply not possible).
* Use the Grafico plugin to export/import model and use a Git repository to host the generated files. This will allows you to work with colleagues and you'll be able to merge conccurent updates, but with the price of some workflows to define.

Regards,

JB

**Comment by stefjoosten** [comment]
Is there any experience with the Grafico plugin for this puprpose? Could you point me towards this person? Thanks in advance!
Stef

**Comment by jbsarrodie** [comment]
@stefjoosten , yes there is. I have been using it for several months (BTW I developed it).

You can find some guidance on its [wiki](https://github.com/archi-contribs/archi-grafico-plugin/wiki).

Don't hesitate to ask questions about it on Archi's forum.

Regards,

JB

**Comment by stefjoosten** [comment]
During the past few months, @bdendulk and I have been collecting some experience with Grafico in combination with Git. Grafico effectively reduces git-storage, because every delta is detected correctly by git and consequently stored efficiently. A great step ahead in multi-user Archi. However, it appears not to be enough. We are experiencing too many merge conflicts. The effect is that we are falling back on single-user mode, with on person (Bart) doing all the version coordination "by hand".

# Analysis
As far as I can tell, this is caused by the Archi-keys. Let me try to explain. Assume Alfred and Bart are working with Archi, each on their own laptops and each with their own copy of model M. Alfred's copy is called A and Bart's copy is called B. Assume that both of these copies are in sync, so both have version v. In short, their situations are identical. Now they start editing. Alfred goes to model A' and Bart goes to copy B'. Assume that Archi has made new keys. The Archi instance of Alfred has no knowledge of what Bart's instance is doing, so assigns new keys that it considers unused. However, Bart's instance does the same. The probability of using the same keys for different things is consequently quite high. This explains the large number of conflicts we are experiencing. (Luckily, Git detects them and prevents havoc...)

**Comment by jbsarrodie** [comment]
Hi,

Thank you for this feedback. I always thought that the UUID generation used inside Archi would prevent the creation of duplicate IDs. My feeling is that this issue could impact not only Grafic but any solution that tries to "link" models (for example the DB plugin developed by Hervé in its shared model mode).

@Phillipus Could we change the way IDs are generated to add something that would make IDs really uniq (e.g. a timestamp concatenated to a UUID) ?

**Comment by Phillipus** [comment]
@jbsarrodie It could be changed. Have to determine what could be truly unique.

**Comment by Phillipus** [comment]
Next beta version will generate IDs of 36 char length from:

String id = UUID.randomUUID().toString();

Example = "e4ae51be-c2d8-4530-bfb1-ab38500efaf7"

**Comment by herve91** [comment]
Hi,

Just for information, I considered from the bigining that 2 distinct models could use the same ID for distinct elements. For this reason, my database plugin changes the IDs the make them unique (in fact, it remplaces the IDs by a concatenation of the element ID, the model ID and the model version).

One of the difficulty of linking models is the versionning, i.e. how to deal with links when models evolve and new versions are created.

If now on the IDs are garantied to be unique, I can link elements using their ID only (and not the concatenation of the element ID, the model ID and the version ID), this will help me a lot.

Thanks and regards
Hervé
