### ISSUE TITLE
Unable to access an artifact from an infrastructure function

### ISSUE THREAD

**Issue by hestratmann** [archimatetool/archi#183]
For symmetry purposes this should be allowed i think.

**Comment by hestratmann** [comment]
ouch, therefore we have a technology object now, sorry for the inconvenience ;-)

**Comment by hestratmann** [comment]
Oke, so where is the technology object?
![screenshot jan 08 09 46 59](https://cloud.githubusercontent.com/assets/24985952/21748528/72c2b2f0-d587-11e6-92c7-7140c1db29b6.png)

**Comment by jbsarrodie** [comment]
Hi,

Technology Object is an Abstract element type in ArchiMate and can't be instanciated in models. Its sole purpose is to simplify the metamodel itself by "grouping" Artifact and Material.

The missing Access relationship from technology behavior to Artifact is is fact due to an issue in official ArchiMate relationships tables (Appendix B) where they are missing. There is an open issue here on github to list all those standard related missing relationship. This issue will be resolved when The Open Group will publish an official errata.

Regards
