### ISSUE TITLE
PNG in Canvas

### ISSUE THREAD

**Issue by glem78** [archimatetool/archi#204]
When you drag & drop a png everything is good but when you want to resize it the bottom of the png is white.

**Comment by Phillipus** [comment]
Could you provide more details - version, OS, size/type of png, steps to reproduce....

**Comment by Phillipus** [comment]
Thanks for info. I'm not seeing anything unusual apart from some banding across the top of the image when resizing. But once resized it looks OK.

**Comment by jbsarrodie** [comment]
One comment for @Phillipus : I've just tested and had issues to really understand...

@glem78 correct me if I'm wrong

In fact this PNG has **transparent background**. When you import it (through DND) the background is transparent in Archi (you can check by putting another colored note behind). But as soon as you resize the PNG, the background gets white.

**Comment by glem78** [comment]
Yes ...

**Comment by Phillipus** [comment]
The problem seems to lie in com.archimatetool.editor.ui.ImageFactory method:

public static Image getScaledImage(Image source, int width, int height)

If the image uses alpha image transparency it is being ignored. I searched Google to try and find a solution but no luck so far. If anyone knows how to copy the alpha data from one image to another let me know.

Also, in com.archimatetool.editor.diagram.figures.diagram.DiagramImageFigure I have set a boolean:

    // This is way faster than Draw2D re-drawing the original image at scale
    private boolean useScaledImage = true;

If this is set to false, it solves the problem but image drawing then becomes very slow.

The ideal solution would be to map the alpha data in the getScaledImage() method.

Any help from the community would be welcome!

**Comment by herve91** [comment]
Hi,

Would this be of any help ?
http://msmshariq.blogspot.fr/2011/07/scaling-transparent-images-in-java.html

Best regards
Hervé

**Comment by Phillipus** [comment]
@herve91 Thanks, but doesn't help. The problem lies in the alphaData bytes of an ImageData. If you have an image of width, height with w*h alphaData bytes then these need to be transposed to the new image size. I've not found an example to do it.

**Comment by glem78** [comment]
Hi guys,
hope this links can help:
http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fswt%2Fgraphics%2FImageData.html
https://eclipse.org/articles/Article-SWT-images/graphics-resources.html

Best regards,
Gilles

**Comment by Phillipus** [comment]
Thanks for the link, but there's nothing there that will solve the problem.

The ImageData bytes and the alpha bytes all have to be transposed. I might change the flag mentioned in comment above and allow user to choose between slow fast rendering.

**Comment by Phillipus** [comment]
This is fixed in Archi 4.8 as we use the slower method to draw scaled images but retain transparency.
