### ISSUE TITLE
[Feature Request] Suppress message for 'Export View As Image to Clipboard'

### ISSUE THREAD

**Issue by rich-biker** [archimatetool/archi#251]
Minor request - Is it possible to have a preference to suppress the message 'Image exported to Clipboard'. Having selected this option, it should be obvious that is what happened. It's an extra click to dismiss the message that can slow you down if there are a number of such exports to be done.

**Comment by Phillipus** [comment]
Seems fair enough to me. I'd like to see if anyone objects to this change, though.

Note - it should really say "Copy image to clipboard". So why did I choose "Export as Image..."? I think because it is actually an export under the hood. The elements are not being copied, and there is no image to copy in the first place.

**Comment by herve91** [comment]
Hi,

I really don't mind for the message. Copy or export are both fine to me.

But having a way to remove the popup would definitively be a nice to have.

Best regards
Hervé

**Comment by jbsarrodie** [comment]
+1 for me

If we go with this option, then we should have both a global setting and a checkbox inside the dialog like this: "[ ] Don't show this dialog again (can be re-enabled through global preferences"

**Comment by Phillipus** [comment]
Fixed in 4.0.3
