### ISSUE TITLE
Question: How to delete missing referenced source element

### ISSUE THREAD

**Issue by alberttwong** [archimatetool/archi#302]
I get a popup when I save that says `relationship has missing referred source element`.   I try to delete all of the (composition) relationships but it won't let me.  What should I do?

**Comment by Phillipus** [comment]
This can happen if the model has somehow lost its integrity. Can you remember what action might have caused this? Did you use an external plugin, for example? Can you say what action might have caused this?

If the model gets into a state like this it will stop you saving it in order to save a bad file. Perhaps you could undo the last few actions in Archi or load the last good version.

**Comment by alberttwong** [comment]
So I manually edited out all the references in the temp.archmate file.   Seemed to solve it.
