### ISSUE TITLE
Installation of collaboration plugin with Archi 4.0.3

### ISSUE THREAD

**Issue by nfigay** [archimatetool/archi#316]
### Version of Archi, Operating System

The bug is about installation of the last graphic plugin version (org.archicontribs.modelrepository_0.2.8.201709191142.zip) on Archi 4.0.3 on MacOSX.
### Expected Behaviour

When selecting the plugin with install plugin, it is expected to be able to  select what is downloaded.

### Actual Behaviour

But the following message is displayed: it is not a plugin zip file.

### Steps to Reproduce the Behaviour
1.Download on mac archi 4.0.3 and the plugin. As there is an automatic unzip when downloading, compress the content of the plugin
2.Launch it using sudo command
3. try to install the plugin with the appropriate selection on the menu

**Comment by Phillipus** [comment]
Hi Nicolas. Archi expects a plugin to be zipped and also looks for a special file ("archi-plugin") to be in the zip file to indicate that it is a plugin.

Is it possible to download and not unzip it? Is this a preference for your browser.

Otherwise you can install manually by copying the jar in the zip to the "plugins" folder in the Archi.app bundle.

**Comment by Phillipus** [comment]
On Safari:

If you would rather Safari just download the .zip file and leave if for you to decide what to do:

    Open Safari 
    Click Preferences
    Under the General tab, uncheck the option Open “safe” files after downloading

**Comment by nfigay** [comment]
Will try and provide feedback. Thanks a lot.

**Comment by Phillipus** [comment]
Please see download instructions at https://www.archimatetool.com/plugins

"Mac users on OS X 10.12 and later may encounter a problem due to Apple's recent implementation of translocation for unsigned apps (basically, unsigned apps like Archi are copied to a read-only area and executed from there, so the plugin can't be copied). We suggest that, before installing a plug-in, you move the Archi app to a different location (for example, move it from the "Applications" folder to "Desktop" or vice-versa.)"

**Comment by Phillipus** [comment]
It should work. I tried it and it's OK. I don't know what could be different on your Mac,

**Comment by Phillipus** [comment]
1. Download Archi and unzip to Desktop.
2. Move Archi to another folder.
3. Open Archi and do the "Install plugin" menu item and install the plugin zip file.

That's what works for me. Check your security settings on Mac, too.

**Comment by nfigay** [comment]
Hi Phil,
I did as you described, but have the same message.
My config: macOS 10.13.1 (High Sierra).
Not sure on how to check the security settings on Mac, in order addressing this issue.
Any suggestions concerning the precise folders I should have a look at?
Best regards.
Nicolas

**Comment by Phillipus** [comment]
You could also move the jar files into the plugins folder inside the Archi.app.

**Comment by nfigay** [comment]
Will try and tell you if it works.
Thanks

**Comment by nfigay** [comment]
I uploaded the last version of the plugin, dated 21/11/2017, and moved the 2 jar files on the app. It works now. I've just to check if no issue when opening current git repository created with the previous version. Can't do it know, I will inform you about the results.
Thanks again.

**Comment by nfigay** [comment]
Hi Phil,
I was able to make the migration from 4.03 to 4.1, without any problem.
Thanks for your support.
Great work :)

**Comment by Phillipus** [comment]
Thanks, Nicolas. I'll close this then.
