### ISSUE TITLE
[feature request] Find/replace elements with specific properties (name and value)

### ISSUE THREAD

**Issue by joao-paulo-c** [archimatetool/archi#318]
Hi.

Eventually I use the properties resource of ArchiMate. The one in which you can set a named property with a specific value to an element. For example, property name "Size" and value "Big".

Then for me it would be useful to find what elements has a property with a specific "name" or even when it has a specific combination of "name" and "value".

One can this field at "Properties" ("Alt+Enter"ing and element), and  "Properties" sheet.

Att.,
João Paulo

**Comment by Phillipus** [comment]
You can use the Search Bar to do this.

**Comment by joao-paulo-c** [comment]
Thanks for your answering. Sorry for opening the feature request. I'll close the issue.

**Comment by MilennialZero** [comment]
Is it possible to mod a base element type to have a pre-defined property
with a populated enum selector on the property line?
So that all new instances of a meta model type have the same property
able to be set by user selection?
Tx

--
  Jon McLeod
  Senior Consultant
  From Here On
  www.fromhereon.com
  +61 457 988 821
  jon.mcleod@fromhereon.com
 
  Jon McLeod
  Director, McLeod Consultancy Pty Ltd
  GPO Box 813 Canberra ACT 2601 Australia
  +61 457 988 821
  jmcleod@thelonius.com.au
  Silver Member The Open Group Architecture Forum



----- Original message -----

**Comment by herve91** [comment]
Hi Jon,

To achieve this, you may use my [form plugin](https://github.com/archi-contribs/form-plugin) that will allow you to create an array with all your elements and a drop-down selector with predefined values (of course, this list of elements can be filtered if you wish).

You'll find more information on the [plugin's wiki](https://github.com/archi-contribs/form-plugin/wiki) and on [Archi's forum](http://forum.archimatetool.com/).

Best regards
Hervé
