### ISSUE TITLE
[feature]: add UML support

### ISSUE THREAD

**Issue by janwilmans** [archimatetool/archi#361]
I would like to be able to also create UML diagrams. Specifically class diagram, but also sequence diagrams and state diagrams using Archi. This, and #202 would make Archi the ultimate software documentation tool. First to give a highlevel overview using business events/services to describe use-cases -> moving to components in the application layer and then drill down into components to see their implementation in UML

**Comment by Phillipus** [comment]
To be realistic about this - this is very unlikely to happen. To implement a UML editor is, I'm sure you can imagine, not a trivial task. :-)

**Comment by Phillipus** [comment]
> with little modification could probably already draw class diagrams

There's no such thing as "little modification".... ;-)

To be clear, this is not something that *I* will implement, but if someone else were to contribute the feature via a plugin then of course that would be ideal. :-)

**Comment by jbsarrodie** [comment]
Hi,As stated by Phil, it is very unlikely that we implement UML modellimg (TBH read: we wont do it).

But, you are free to "simulate" UML using existing ArchiMate constructs. What is missing is a way to make properties visible in the figure on the diagram. This would solve several needs like classe diagram or ERD.

May I suggest you contribute a plugin for that use-case ?

**Comment by Phillipus** [comment]
Just to add - I don't intend to be dismissive or rude about this feature request. It's just that I think it's important to be realistic about what I, or @jbsarrodie, will, or won't (or can't), implement. This way, everyone is clear about things. :-)

**Comment by janwilmans** [comment]
I really appreciate the candid feedback. I'm mostly interested in getting the integration working, so maybe there is already a UML plugin for eclipse that could be leveraged, and we only have to create a link-option to integrate the two? for example, if a component could have a link to an plant-uml file and the html-export could render that, this could maybe serve the same purpose?

**Comment by Phillipus** [comment]
Yes, there is an Eclipse-based [UML editor/plugin](https://www.eclipse.org/modeling/mdt/?project=uml2) but it won't integrate with Archi.

Eclipse is supposed to be an IDE that integrates plug-ins that fulfil the common framework. And for that you get all the Java editing, CSV integration (yes, CSV), and other stuff. But Archi uses only some of the Eclipse framework (the Rich Client Platform) and this spares the user from all the cruft - Archi users don't want to see menu items like "Refactor Java Class". And so, because Archi uses a sub-set of the Eclipse framework, the UML plugin won't integrate with it.

**Comment by janwilmans** [comment]
I see, I understand that, I frankly the clean interface is one of the things I love about Archi

**Comment by Phillipus** [comment]
But...perhaps another way to do this is via the internal Browser component. The Report Preview uses a native Browser component for rendering. Perhaps a JS UML editor could be spawned in an internal Browser instance and link to an Archi model via some link code.

**Comment by MilennialZero** [comment]
Me too. The UI for Archi is better than any of the bloatware vendor
tools that cost zillions.
Sidebar: I'm concerned that a lot of the functions I'd prefer to have tightly integrated into the core code are plug-ins that I have to download from github and install myself. Developers have no problem with this, but Archi is not a tool for developers, guys, it's a tool for graduate business analysts. That's your customer experience persona right there. Graduate business analysts.
Also - the plug-in experience isn't giving me a consistent user
experience.
I'm happy to configure features and functions in panels inside the tool.
But if I have to write my own script code to get the tool to do
something for me, you've lost me.
Also - I have an aversion to third-party tool plug-ins because there's a
slight chance they could be infested with malware. I can't understand
the new-fangled source code you millennials are writing these days, but
I'd want a guarantee that every line of code for all Archi plug-ins has
been subject to very close scrutiny. Every time it's checked back in.
Open source is great. But it's not without risks. Those risks are more
manageable with open source, but they still need to be managed.
Cue argument. 

--
  Jon McLeod
  Senior Consultant
  From Here On
  www.fromhereon.com
  +61 457 988 821
  jon.mcleod@fromhereon.com
 
  Jon McLeod
  Director, McLeod Consultancy Pty Ltd
  GPO Box 813 Canberra ACT 2601 Australia
  +61 457 988 821
  jmcleod@thelonius.com.au
  Silver Member The Open Group Architecture Forum

----- Original message -----

**Comment by janwilmans** [comment]
That sounds good, I'll install the IDE and stuff see if I can build

**Comment by janwilmans** [comment]
I'll try to contribute something to enable the described usecase.

I've started by installing the development environment, java8 sdk and Oxygen.3 , nice documentation on the website btw. Rare to see such a good description on how to contribute. I have problem building though: 
![image](https://user-images.githubusercontent.com/5933444/37996900-d2ffcc82-3208-11e8-8d18-8ef4b0c8ecb7.png)

For some reason GraphConnection (part of Zest?) is not compiling? 
Looks like I may be missing a library I need to install?

**Comment by Phillipus** [comment]
@MilennialZero 

> I'm concerned that a lot of the functions I'd prefer to have tightly integrated into the core code are plug-ins that I have to download from github and install myself.

> Also - the plug-in experience isn't giving me a consistent user experience. 

I agree Jon, but if the plug-in is written by a third party then I can't support it.

**Comment by jbsarrodie** [comment]
>For some reason GraphConnection (part of Zest?) is not compiling?
>Looks like I may be missing a library I need to install?

I had to reinstall my dev environments two weeks ago and follow the procedure: it works flowlessly, so you might have miss something.

Have you set the platform using "com.archimatetool.editor.product/archi.target" (and wait enought for Eclipse to download all needed things)?

**Comment by Phillipus** [comment]
UML is not part of Archi.
