### ISSUE TITLE
Show Relationship Name option in diagram

### ISSUE THREAD

**Issue by ranjithkmoorthy** [archimatetool/archi#399]
Adding the relationship name to the connector has been a great help for the adoption of Archimate diagrams when i started creating sharing them with my audience. Initially i used to get a confused face when my audience saw a model for the first time. I had to manually add relationship text to each connector to make sure everybody can read and understand it without textual description added which is time consuming. To make models readable it would be great to have an setting to switch ON and OFF the relationship text. Example of what im talking about attached below
![image](https://user-images.githubusercontent.com/18426439/45712073-41245000-bb40-11e8-8101-1220b6ffffce.png)

**Comment by herve91** [comment]
This jArchi script allows to replace the label by changing the relationships name, which may not be what you're searching for.

My I suggest an alternative solution ...

To change the label without changing the relationships name, you may use my  [specialization plugin](https://github.com/archi-contribs/specialization-plugin) and set your relations label to something like _**${${view:property:relationships_label}}**_.
![image](https://user-images.githubusercontent.com/9281982/45742677-d2f09380-bbfa-11e8-8a48-23336720518d.png)



By default, the relationships labels will not be shown:
![image](https://user-images.githubusercontent.com/9281982/45742746-eef43500-bbfa-11e8-8c44-91efaa96901c.png)



If you create a property **_relationships_label_** with value **_name_** in your view, the relationships labels will be shown:
![image](https://user-images.githubusercontent.com/9281982/45742773-ffa4ab00-bbfa-11e8-8456-72c125c9e659.png)



How it works: 
The labels are compound of two variables, one enclosed into the other --> the inner variable will be analyzed before the outer one:
- The inner variable **_${view:property:relationships_label}_** will be replaced by the value of the property _**relationships_label**_ of the view (so either an **_empty_** value or **_name_** in my example)
- The outer variable will therefore be either **_${}_** which will lead to an empty label, or **_${name}_** wich will be replaced by the name of the relationship

Please note that when you modify the view property, the view needs to be refreshed in order to show or hide the labels. The easiest way is to close and reopen it.

Please do not hesitate to open a case on my plugin's GitHub in case you require more information.

Hope this helps

Best regards
Hervé

**Comment by gimatdinov** [comment]
Use the [ArchiAnnotation plugin](https://github.com/gimatdinov/gimatdinov.archiannotations) v0.3. Set property %HCL for diagram - Hide Connection Label locally.

**Comment by brianjwilson** [comment]
This is kind of an old thread to reignite, but I found an interesting workaround in that you can select a whole batch of relationships in the outline view of the _Models_ window and then type a name in the Main Properties box and rename them all at once, causing those names to appear in diagrams that include those relationships. I understanding that renaming them might not be the actual intent but for me, lacking an actual display label field on the objects, it was quite a bit simpler than some of the other strategies discussed here.

**Comment by Phillipus** [comment]
Actually I have some code to hide/show relationship names. It's in the "features" branch here in GitHub. Just waiting for other things to mature first,

**Comment by Phillipus** [comment]
This is implemented
