### ISSUE TITLE
HowTo Package Mac Version

### ISSUE THREAD

**Issue by holiday-sunrise** [archimatetool/archi#413]
Try to package for an Mac. But with to given pom it will not package. Whats wrong.  Release Source 4.3.0.

**Comment by Phillipus** [comment]
Can you provide more detail in what you doing? How is Maven building it? Any errors? OS?

If you use the archi.product file you can actually export a packaged build from the "Eclipse Product Export Wizard"

**Comment by holiday-sunrise** [comment]
hi i build it in a console without running eclipse.  is that wrong . we would like to use archi but the securtiy policies did not allow to use MacApp without a valid zertificate

for an Eclipse Product Export Wizard" i need a running eclipse.  

kind regards

**Comment by Phillipus** [comment]
Are you calling the top-level root pom.xml file?

But be aware that the product files that are produced by Maven cannot be used "as is". The files and directories have to be re-arranged to produce a working .app file.

Can you add a certificate to the existing .app file?

**Comment by holiday-sunrise** [comment]
>> Are you calling the top-level root pom.xml file?

Yes

>>But be aware that the product files that are produced by Maven cannot be used "as is". The files and >> directories have to be re-arranged to produce a working .app file.

What have to be re-arranged. Curently i have after a build no .app file

**Comment by Phillipus** [comment]
I've just taken a closer look at this (it's a long time since I did the pom.xml files).

- The top-level pom.xml file is configured for build and unit tests. This is used by Travis CI for automated testing.
- To produce a product build the pom.xml file needs to be edited. I have just now committed a new pom.xml file containing comments on how to do this. You can uncomment some lines and remove one line to achieve this.
- When Maven builds the product binary zip files they are placed in the `\com.archimatetool.editor.product\target\products` directory
- In my experience the produced zip files are not very useful as they require additional post processing to create a proper final product. Especially so for Mac.

I don't use the Maven pom.xml files for final builds. I use Eclipse's Product Export wizard and then a series of post-processing scripts to copy and move files into their correct locations.
