### ISSUE TITLE
Specializations

### ISSUE THREAD

**Issue by jvdongen17** [archimatetool/archi#417]
Given charter 15 of the specification a specialization is a std element with a special objective.

I need a specialization of a capability and want to add that to the palette.

**Comment by jbsarrodie** [comment]
Hi,

For the moment Archi does not directly support language customization. The best you can do is to manually add a "Stereotype" property on concepts to keep track of the specialization name. You can then use Herve's Specialization plugin to change the concept's label to "Concept_Name <<Specialization_Name>>" and (if needed) an alternate icon. And instead of doing all this manully for each new concept, you can prepare it in a ["Toolbox" that can be used as a custom palette](https://github.com/archimatetool/archi/wiki/Pattern-based-modelling-with-Archi).
