### ISSUE TITLE
Tool fails to open on Mac

### ISSUE THREAD

**Issue by shashig** [archimatetool/archi#445]
### Version of Archi, Operating System
Archi 4.3.3 on macOS version 10.14.13 
### Expected Behaviour
The application should open when double clicking on Archi.app

### Actual Behaviour
Get error: “Archi.app” is damaged and can’t be opened. You should move it to the Trash.

### Steps to Reproduce the Behaviour
1. Download from www.archimatetool.com 
2. Unzip to extract the contents
3. Double click on Archi.app

**Comment by shashig** [comment]
![image](https://user-images.githubusercontent.com/988944/52988275-997bb880-3424-11e9-9dae-107b06947f87.png)

**Comment by Phillipus** [comment]
On the download page we have a note to explain this:

_Note – when launching Archi on OS X for the first time you may see a dialog box that states that “Archi can’t be opened because it is from an unidentified developer.” Control-click or right click the icon of the app. Select “Open” from the top of contextual menu that appears, then click “Open” in the dialog box. Or you may see the message “Archi is damaged and can’t be opened. You should move it to the Trash.”, to solve this see [this](https://www.tech-recipes.com/rx/45404/mac-downloaded-app-is-damaged-and-cant-be-opened-error-solved/)._

https://www.tech-recipes.com/rx/45404/mac-downloaded-app-is-damaged-and-cant-be-opened-error-solved/

**Comment by Phillipus** [comment]
Closing as resolved.
