### ISSUE TITLE
[Feature Request] XMI export

### ISSUE THREAD

**Issue by dlehammer** [archimatetool/archi#457]
In-order to be able to migrate to Archi and Open Exchange format, from [Enterprise Architect](https://sparxsystems.com/products/ea/), support for [XMI](https://www.omg.org/spec/XMI) export is missing.
(Enterprise Architect v14 supports XMI v1.1, v2.1 ... v2.5.1 export)

Is this a sensible request **?**
(or does it clash with scope / road-map / licences / etc. )

**Comment by Phillipus** [comment]
Archi imports/exports the Open Exchange format. Are you asking for Archi to export to EA format? Don't really understand what you're asking for.

**Comment by jbsarrodie** [comment]
If you currently use Sparx EA with ArchiMate metamodel, you have to use a recent version that includes the ability to export to the Open Group ArchiMate Exchange File Format (older version of Sparx require some third party, paid, plugin).

If you don't use the ArchiMate metamodel, you won't be able to export anything that Archi can import easily. XMI is only meaningful for UML (in fact MOF) based model, and is limited to model itself (entities and relationships) and doesn't contain vues (ie. diagrams).

In such situation, you're usually on your own. FWIW, in this context, doing such migration usually involves:
* Exporting model content and converting it to the CSV format supported by Archi
* Importing those CSV in Archi
* Manually recreating all views, maybe with the help of some jArchi scripts :-(

**Comment by dlehammer** [comment]
Hi @Phillipus & @jbsarrodie,

Thanks for the swift responses!

Hmm, this derailed a lot faster than I anticipated, I'll try to describe the missing feature as concise as possible :)

## Feature:
### Export model from ["Open Group ArchiMate Model Exchange File Format"](https://www.opengroup.org/open-group-archimate-model-exchange-file-format) to ["XML Metadata Interchange Specification"](https://www.omg.org/spec/XMI)(XMI) file-format.

Ie. XMI is another international standard for model exhange, and is supported by many tools ex. Modelio, IBM Rational, Enterprise Architect...
Hence I was surprised that this is an unsupported feature in Archi.

## Clarification
> Are you asking for Archi to export to EA format?

No, the goal is to move from the current setup based upon EAs proprietary eap file-format, to "Open Exhange" for modeling.
(This should already be possible by exporting to "Open Exhange" from EA and importing into Archi)

The current workflow is also dependent on XMI export of the model, as XMI is used by consumers of the model that require a machine-readable format.
This is currently handlede by EA, and is where Archi currently falls short.

**Comment by Phillipus** [comment]
Still don't understand what you want. Archi doesn't export to XMI as @jbsarrodie said "XMI is only meaningful for UML"

**Comment by jbsarrodie** [comment]
>Export model from "Open Group ArchiMate Model Exchange File Format" to "XML Metadata Interchange Specification"(XMI) file-format.
Ie. XMI is another international standard for model exhange, and is supported by many tools ex. Modelio, IBM Rational, Enterprise Architect...

In fact this doesn't really makes sens. XMI is not a generic standard for model exchange, it only concerns MOF based metamodels. The tools you provide as examples are all UML modelling tools at their core.

ArchiMate is not based on UML nor MOF, Thus an ArchiMate model can't be exported to XMI. This is not related to Archi. In fact no tool can export an ArchiMate model to XMI. If one claims to do so it is only because its internal way of managing ArchiMate is based on MOF, but this is not part of the standard.

Last, as said previously, an XMI export would not be meaningful as it wouldn't contain views/diagrams. That's the reason why The Open Exchange File format is not based on XMI.

So unfortunately, this feature request won't be implemented. Sorry.

**Comment by dlehammer** [comment]
@jbsarrodie 

> Last, as said previously, an XMI export would not be meaningful as it wouldn't contain views/diagrams.

I never said that I desired a 1:1 export of all the model-data. As far as I can tell, EA (and other tools) XMI export is limited to the machine-readable parts of the model, for later code-generation etc.
Ie. a subset of the model-data

I was hoping Archi would consider adding similar XMI support :)
Oh well, guess we'll stick with EA for now.

**Comment by Phillipus** [comment]
As I said, it's possible to export the conceptual data to XMI if someone would like to contribute a plug-in to do so.

> I was hoping Archi would consider adding similar XMI support :)
> Oh well, guess we'll stick with EA for now.

I'm going to take this opportunity to say something now that I need to say:

There have been several requests here and in emails lately along the lines of "I and my stakeholders in our company need feature x in Archi, (paid) products x and y have got these features, why hasn't Archi?"

- Archi is free
- Archi is open source
- There's only one person who codes Archi full time - me
- I work on this voluntarily (usually every day)
- Others can contribute a feature as a plug-in if they like
- If Archi's not right for you as it is, fine, go buy product x

Phil

**Comment by jbsarrodie** [comment]
> I never said that I desired a 1:1 export of all the model-data. As far as I can tell, EA (and other tools) XMI export is limited to the machine-readable parts of the model, for later code-generation etc.
> Ie. a subset of the model-data
> I was hoping Archi would consider adding similar XMI support :)

OK, I guess I better understand why we don't understand each other ;-)

ArchiMate is absolutely not meant to be used for code-generation and such things. That's the reason why (between other things) there is no multiplicity or distinction between classes and instances. This is also because of this that ArchiMate is not base on MOF. So this makes XMI impossible and almost nonsens for ArchiMate. Such XMI would be **tool dependant** and not standard because XMI is simply a standard way to serialize a non standard metamodel (based on MOF).

If you want some to automate things based on the content of an ArchiMate model, you have to either rely on the Open Exchange File Format directly (which is XML based) or use the native serialization format of Archi which is based on Eclipse Modelling Framework and is very (very) similar to XMI.

> Oh well, guess we'll stick with EA for now.

Might be the best option for your use-case.

BTW (but it's only a personal opinion of course) Sparx and similar very generic modelling tools are the worst tools for ArchiMate as there is some very fundamental differences between everything based on MOF (UML, SYSML, BPMN...) and ArchiMate.
