### ISSUE TITLE
[improvement] Delete from Model consistent context menu item

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#504]
### Version of Archi, Operating System
4.4 WIN10

### Actual Behaviour
Context menu in the view lists "Delete from Model" action - that is correct. 
Context menu in the model tree lists "Delete" action.

Please make the wording consistent. 

### Expected Behaviour
Right click on model's item in the model tree should reveal context menu with "Delete from Model" action (instead of Delete)

It is only the naming improvement for consistency, functionality is already there.

**Comment by Phillipus** [comment]
This is deliberate.

The "Model Tree" represents the concepts in the model and so the global "Delete" menu item applies to deleting the concept. In a View, the global "Delete" menu item deletes the visual object. This is why we have a separate "Delete from Model" action.

There will always be a global "Delete" menu item, and this can't be changed.

**Comment by radeksvarz** [comment]
@Phillipus I assumed it was deliberate :) 

> Having another look at it, it might be possible to change "Delete" to read "Delete from Model" in the tree, 

Indeed that is the proposal 👍 

> Edit - it becomes complicated when one selects a sub-folder in the Models Tree. For this a simple "Delete" label might make more sense as a folder is not really part of an ArchiMate model.

I disagree on this as deleting subfolder also deletes its content.

**Comment by Phillipus** [comment]
As we know, normally one would have just one "Delete" global menu item. However a View demands two menu items, "Delete from Model" and "Delete from View".

When a View is opened an additional menu item, "Delete from Model" is added under the main "Edit" menu and the global "Delete" menu item's text is changed to read "Delete from View".

However, when the focus is put back on the tree we now have these two menu items:

![Screen Shot 2019-07-22 at 10 55 07](https://user-images.githubusercontent.com/600504/61623842-5c378300-ac6f-11e9-9391-9cc931ebf0c4.png)

If we changed "Delete" to read "Delete from Model" we would then see two of these. Not good.

Because of the way menu handling works (Eclipse) you can't remove the additional "Delete from Model" menu item in this context or re-use it.

**Comment by radeksvarz** [comment]
Running 4.4 I can see the current behaviour as:

A) - global menu in the view context - OK:
![image](https://user-images.githubusercontent.com/6020891/61727318-66db4080-ad73-11e9-9e66-fc96802b7378.png)

B) - global menu in the model tree context when focus is on the tree item:
![image](https://user-images.githubusercontent.com/6020891/61727401-94c08500-ad73-11e9-965d-90384d4ee2d9.png)

 --- honestly I was not aware of this. And this is even more confusing. Why not aware? I merely use global menu - I rather use right click - context menu, making sure with what I am working.

C) - context menu in the view context - OK:
![image](https://user-images.githubusercontent.com/6020891/61727576-e406b580-ad73-11e9-9fb9-877c8ecceff6.png)

D) - context menu in the model tree context - this one I was talking about **to be renamed to "Delete from Model"**:
![image](https://user-images.githubusercontent.com/6020891/61727651-03054780-ad74-11e9-8d19-061b4d8bfb11.png)

Regarding the case B - that is unfortunate as Delete in this case is very destructive. I would rather disable Delete action and enable Delete from Model action in the global menu for this case (UX wise - I am not sure about the changes in menu setup within Eclipse).
