### ISSUE TITLE
[Experiment] Use coloured folder icons

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#545]
I was thinking the folder icons in the Models Tree are a bit bland and not really suited for their purpose, a container. So I've experimented with coloured folders:

Before:

![before](https://user-images.githubusercontent.com/600504/67621583-7e114a80-f808-11e9-8144-275a8329c495.png)

After:

![after](https://user-images.githubusercontent.com/600504/67621588-85d0ef00-f808-11e9-9290-befe108d3bf3.png)

Code is in the "coloured-folders" branch.

**Comment by rchevallier** [comment]
It is an excellent idea

**Comment by Phillipus** [comment]
I'll ensure that it is optional in Preferences so users can have the old folders if they want. We can gets user feedback.

**Comment by Phillipus** [comment]
![dark](https://user-images.githubusercontent.com/600504/67625336-c9415280-f834-11e9-975f-90cac75f23f2.png)

**Comment by jbsarrodie** [comment]
Well, that's not my cup of tea (I'm one of those who like monochrome/flat icons). But if optional this won't hurt.

I wonder if this could not be achieve through theme (and thus open to customization) instead of through code and options in Preferences.

**Comment by Phillipus** [comment]
> I wonder if this could not be achieve through theme (and thus open to customization) instead of through code and options in Preferences.

 I don't know how to do that, because the Tree Label Provider class has to have a reference to an icon file. It may be possible to externalise the paths to icons, though. in some type of configuration file.

> I'm one of those who like monochrome/flat icons

At some point we could create a theme for colours and workbench, and externalise the paths to icons and then have a flat icon set.

**Comment by Phillipus** [comment]
Should this be turned on or off by default in Preferences?

If on by default users will know about it but might not know they can turn it off in Prefs if they don't like it.

If off by default users might not know about it.

**Comment by Phillipus** [comment]
I can turn it on by default for 4.6 Beta 3, and await feedback. The decision for on/off can be made for 4.6 final release.

**Comment by Phillipus** [comment]
We could at least change the existing folder icons from the MS-style "opened" folder to a flatter one:

![f3](https://user-images.githubusercontent.com/600504/67632671-4b199600-f89e-11e9-876a-6477228edb0e.png)

**Comment by jbsarrodie** [comment]
>We could at least change the existing folder icon from the MS-style "opened" folder to a flatter one:

Yes, that's a good idea.

>Should this be turned on or off by default in Preferences?

I would suggest to turn it off by default.

Thinking more about it I know what was disturbing me in this: it's not the fact I prefer monochrome theme, it's the fact that by using a per layer coloring, we actually reinforce people in thinking color has a meaning in ArchiMate while it doesn't. I have met a lot of people deeply thinking that business elements can only be yellow, to the point that they name layer by their color (yellow layer, blue layer...). My feeling is that we should counter this because these colors (slightly) make sens only for people into ArchiMate, but the whole point of ArchiMate is to communicate with other stakeholder who don't know the standard (and don't have to learn it).

In this spirit, I would even suggest to remove color on icons used in the palette, but this would also requires to add some kind of headers so that people quickly recognize the sections.

Some would think that this is extreme (and it might be), but I think we should go along this line if we want Archi to help people "learn ArchiMate the right way". Of course, if in some context it makes sens to use per layer color, then Archi could provide a way to support it, but this should not be the default IMHO.

**Comment by Phillipus** [comment]
I agree about not reinforcing the ArchiMate layer colours.

I think my aim in trying the coloured folders is that the UI in the tree looks "samey" with the one folder style and colour. I wanted to at least somehow distinguish each folder type in some way, and colouring seemed like an obvious choice...and so which colours to use? The layer colours were chosen as a convenience. ;-)

> In this spirit, I would even suggest to remove color on icons used in the palette, but this would also requires to add some kind of headers so that people quickly recognize the sections.

After 4.6 we can devote time to a UI sprint (as I mentioned elsewhere) and this could be included in that.

But at least this experiment allows us to see what works and what doesn't.

**Comment by Phillipus** [comment]
Well, it took a bit longer to implement but I now have the perfect solution:

![clever](https://user-images.githubusercontent.com/600504/67637974-dc592e80-f8d7-11e9-92a6-b16343679014.png)

(The default is all folders are the same yellowish colour.)

**Comment by rchevallier** [comment]
Suggestion: set the colour folder option as a "folder color" entry inside each section (Strategy, ...) instead of creating a new section

**Comment by Phillipus** [comment]
> Suggestion: set the colour folder option as a "folder color" entry inside each section (Strategy, ...) instead of creating a new section

Sorry, don't understand...

**Comment by rchevallier** [comment]
Let's make an example for the Strategy folder:

Instead of having a "Strategy" option inside the "Folder colours" section of the "Colours and Fonts" preference, move this option as a "Strategy Folder" option inside the "Strategy elements fill colours".

So everything about the Strategy layer colours is inside the same section. Likely also rename the section "Strategy elements fill colours" as "Strategy items fill colours" or something else as it is not only about elements. You won't need then the new section "Folder colours"

NB: very minor suggestion

**Comment by Phillipus** [comment]
Those sections are only for default element fill colours. I want to keep the folder colours separate from the rest of the fill colours as they are for the app not for each model.

**Comment by rchevallier** [comment]
Makes sense. Thanks for the explanation

**Comment by Phillipus** [comment]
Close this one now that 4.6 is released.
