### ISSUE TITLE
Archi cannot run on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by fluxens** [archimatetool/archi#553]
### Version of Archi, Operating System
Archi 4.6.0
macOS 10.15.1 (19B88)

### Expected Behaviour
Archimate should run when opening the Archi.app

### Actual Behaviour

An error message pops up (see below). This is related to #445, however the solution proposed there does not work in macOS Catalina. The setting "Allow apps downloaded from:" can no longer be changed to "Anywhere" due to Gatekeeper.

### Steps to Reproduce the Behaviour
1. Download Archi for macOS
2. Run it (double click or right click open)
3. Observe the error message 

<img width="532" alt="image" src="https://user-images.githubusercontent.com/22811368/68664116-1b29ee00-0540-11ea-9568-932dd7b360ae.png">

**Comment by Phillipus** [comment]
This is a known issue and we have documented this:

1. In the special README!.txt file that ships with Archi on Mac.
2. At the point of download on the download page
3. In the Archi FAQ
4. On the Archi forum https://forum.archimatetool.com/index.php?topic=765.0

**Comment by Phillipus** [comment]
And for anyone who is unable to read any of those, here it is again:

If your Mac states that it cannot run Archi because it is "damaged" (it isn't) run the following command from the Terminal app.

     sudo xattr -r -d com.apple.quarantine Archi.app

This will remove the quarantine bit from the Archi application to allow it to run.

(You will need to adjust the path to Archi.app or change the current directory to the location of Archi.app in Terminal.)

For more information see https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/

**Comment by fluxens** [comment]
Thanks for the reply. tbh, I did not notice this on the download page.
