### ISSUE TITLE
[Feature Request] Warn when changing a relationship end and other views are impacted

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#558]
When editing a view, a user can move the ends of a relationship. This updates the underlying relationship in the model and immediately affect other views in which the same relationship was present. This can lead to views being no more valid without the user noticing it.

When moving a relationship's end, I'd suggest that Archi checks if the relationship is used on other views and (if any) show a warning dialog similar to this one:
![image](https://user-images.githubusercontent.com/5757396/69240163-2a421900-0b9c-11ea-8b7c-8c9a80edae0f.png)

**Comment by Phillipus** [comment]
Unfortunately, this is not possible because of the way GEF works in `ArchimateDiagramConnectionPolicy`.

When reconnecting, for each drag (and the completed reconnect) action, the Policy asks for a Reconnection Command (that in itself is a very expensive operation). When the reconnection is completed and the Command is executed it is then too late to display a dialog. I.e there is no way to veto the execution of the Command.

I tried some tricks like interrupting the Command's execute() method but this messes up the Command stack.

The best I've been able to do is show an information dialog that the connection is used in other Views and has changed after the operation. At this point the user can Undo.

**Comment by Phillipus** [comment]
Committed to `show-connection-warning` branch.

**Comment by jbsarrodie** [comment]
>The best I've been able to do is show an information dialog that the connection is used in other Views and has changed after the operation. At this point the user can Undo.

Seems good. But I wonder if at this stage we could not pretend that it still hasn't been applied and then if the user choose "no" to the confirmation dialog, then we undo the whole operation ?

**Comment by Phillipus** [comment]
Tried that. At that point the command has been executed but not put on the Command Stack so Undo is not possible. I tried lots of things ;-)

**Comment by Phillipus** [comment]
> Tried that. At that point the command has been executed but not put on the Command Stack so Undo is not possible. I tried lots of things ;-)

Actually, if we call the Undo command with `Display#asyncExec()` we can do this. So I've committed this change.

**Comment by Phillipus** [comment]
Closing this as it is implemented for the next version. Please re-open if any issues are found when released,
