### ISSUE TITLE
[Feature Request] Add option to move Connection Layer behind Primary Layer

### ISSUE THREAD

**Issue by VinceAxe** [archimatetool/archi#590]
On the last version of Archi (I can't remember if it was the same behavior before)

When I add a new element (even a visual note)
And I want to use "Bring to front" in order to put it over relations 

It does not work and the relations stays in front of the element
<img width="177" alt="Untitled" src="https://user-images.githubusercontent.com/43959255/76100957-e0a3ff80-5fcd-11ea-80a9-a773e32c8830.png">

**Comment by Phillipus** [comment]
This is because connections are drawn on a different layer than nodes, and this layer is above the drawing layer of nodes. So a "Bring To Front" above connections is not possible.

**Comment by Phillipus** [comment]
As the connection layer's position can only be set for the whole diagram I've renamed the feature request.

@jbsarrodie I've just done some testing and it is possible to move the connection layer behind the primary layer so that connections are drawn behind nodes. I don't know if this is useful or even if there are side effects. What do you think?

The code is in branch `connection-layer`

![c](https://user-images.githubusercontent.com/600504/76106614-231a0c00-5fcf-11ea-93ad-5c890e4993e4.png)

**Comment by jbsarrodie** [comment]
Hi. I don't really like this option because if a connection is drawn behind an element then people will understand it as two relationships (one to the element and one from the element).

@VinceAxe what was the use-case?

**Comment by Phillipus** [comment]
> Hi. I don't really like this option because if a connection is drawn behind an element then people will understand it as two relationships (one to the element and one from the element).

That's a good reason. Probably why the connection layer is in front of the primary layer by default in GEF.

**Comment by Petrolevb** [comment]
The idea behind this use case was to make a legend, in this case we have 2 times 9 Flow that are about referentials and golden data. 
Putting all of them in a corner but with a specific (overlapping) legend
I understand the side effect of two relationship instead of one ... but there are similar side effects with elements that can hide some others as well

(Might it even be a way to represent an ESB ?)

**Comment by rchevallier** [comment]
I think the risk of misinterpretation is too strong.

**Comment by Phillipus** [comment]
> 
> 
> I think the risk of misinterpretation is too strong.

I agree, I don't think we will implement this for general usage.

**Comment by Phillipus** [comment]
Shall we close this issue?
