### ISSUE TITLE
Switching view tabs with hotkeys

### ISSUE THREAD

**Issue by smirnoww** [archimatetool/archi#686]
Hello!
It would be a pleasure to switch view tabs via ctrl+TAB and ctrl+shift+TAB
![archiCtrlTab](https://user-images.githubusercontent.com/6284636/97847884-57ca9880-1d01-11eb-943f-de67a7cdff1d.png)

**Comment by Phillipus** [comment]
Those key bindings are not possible as they are reserved in the system. There are some navigation shortcuts you can see in the Window->Navigation menu.

**Comment by jbsarrodie** [comment]
> There are some navigation shortcuts you can see in the Window->Navigation menu.

@smirnoww : The ones you should look at are CTRL + F6 and CTRL + SHIFT + F6.

@Phillipus : I find the menu entries name misleading as they use the term "View" for Eclipse Views, not ArchiMate view, and "Editor" instead of (ArchiMate) "View". I'd suggest to:
- use "Pane" instead of "View"
- use "View" instead of "Editor"

**Comment by Phillipus** [comment]
@jbsarrodie I can't change them, they come with Eclipse.

**Comment by Phillipus** [comment]
> @jbsarrodie I can't change them, they come with Eclipse.

Scrub that...there might be a way...

**Comment by Phillipus** [comment]
The menu item text can be changed but the text on the popup that appears cannot be changed.

<img width="441" alt="Screenshot 2020-11-03 at 12 26 35" src="https://user-images.githubusercontent.com/600504/97985215-e4438c80-1dcf-11eb-9141-03de1cc04761.png">
