### ISSUE TITLE
Unable to launch archi on Mac

### ISSUE THREAD

**Issue by Angelo-FSL** [archimatetool/archi#722]
### Version of Archi
Archi-Mac-4.8.1

### Archi Plug-ins
No

### Operating System
MacOs Catalina 10.15.7 (19H524)

### Expected Behaviour
Being able to launch the archi app

### Actual Behaviour
App crashes (doesn't run) with following message: "An error has occurred" See the log file.

log file details:
!SESSION Tue Apr 06 14:38:20 COT 2021 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2021-04-06 14:38:20.073
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.compatibility.state_1.2.200.v20200915-2015.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2021-04-06 14:38:20.138
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
    at java.base/java.net.URLClassLoader.findClass(Unknown Source)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:650)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

### Steps to Reproduce the Behaviour
1. Go to executable file
2. Double clic
3. App crashes

**Comment by Phillipus** [comment]
Is this a fresh install of Archi? Have you used an older version of Archi before this one?

Archi stores preferences and configuration files in this folder:

`<your_home_folder>/Library/Application Support/Archi4`

Please ensure that you have write access to that folder.

You could also try deleting this folder:

`<your_home_folder>/Library/Application Support/Archi4/.config`

Because the folder has a dot in it (`.config`) it will be hidden unless you show hidden files in the Finder (Coomand + Shift + "." will toggle hidden files.)

**Comment by Angelo-FSL** [comment]
I deleted  the .config folder and it worked!Thank you!.

**Comment by tywilliamferguson** [comment]
> I deleted the .config folder and it worked!Thank you!.

This also worked for me just now on version 4.8.1 of Archi - many thanks! (On Mac)

*Full re-download didn't worked beforehand only when I deleted 'Archi4' folder in 'Application Support' did it fix the issue.
