### ISSUE TITLE
fullscreen is not working on linux

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#729]
### Version of Archi
4.8.1

### Archi Plug-ins
no

### Operating System
linux, X11, KDE

### Expected Behaviour
when F11 is pressed or view-fullscreen is selected model view should go to full screen

### Actual Behaviour
actually this happens
![Screenshot_20210506_101321](https://user-images.githubusercontent.com/11752339/117258024-32a41780-ae55-11eb-9885-ede335ed2f63.png)

Also the background colour changes from light in windowed mode to dark in fullscreen - this happens on windows too. Dark theme on both.

### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
This feature has always been problematic, especially on Linux. It could be due to your screen size, but I don't know as I can only test it in a VM on a small screen where it is working for me.

It might be better to remove this feature if it's unreliable. Unless anyone wants to have a look at it:

https://github.com/archimatetool/archi/blob/master/com.archimatetool.editor/src/com/archimatetool/editor/diagram/actions/FullScreenAction.java

**Comment by Phillipus** [comment]
> Also the background colour changes from light in windowed mode to dark in fullscreen - this happens on windows too. Dark theme on both.

I have a fix for this particular issue in the next build. This is to do with #730
