### ISSUE TITLE
Feature request: Specializations should have documentation and properties

### ISSUE THREAD

**Issue by heikkil** [archimatetool/archi#812]
I am baffled by the XML and GUI implementations of specializations in Archimate.

It introduces an XML tag 'profile' with three attributes: name, id, and conceptType. It has a custom user interface that allows for creating, modifying, and deleting these specializations.

As a result, they can not have documentation nor properties, both that I'd like to them have. Properties would help to keep track of  name values in various languages, and the appearance of the name could be  modified by label expressions.

Could specialisations be just special elements that do not have a graphical representation and as a consequence no 'Appearance' in the 'Properties' pane where all the other aspects of them could be edited? They could have their own folder below 'Relations' in the Model pane.

They might be some wider compatibility issues with the XML usage that I am not aware of, but from the GUI user's point of view, my vision would make more sense than the current one. Maybe the profile tag could be expanded to use documentation and property tags?

**Comment by Phillipus** [comment]
We will work further on Specializations (and Profiles).

We discussed adding Documentation [here](https://github.com/archimatetool/archi/issues/705#issuecomment-901758211).

**Comment by jbsarrodie** [comment]
> I am baffled by the XML [...]
>It introduces an XML tag [...]
>They might be some wider compatibility issues with the XML usage that I am not aware of, but from the GUI user's point of view, my vision would make more sense than the current one. Maybe the profile tag could be expanded to use documentation and property tags?

`.archimate` file are the internal persistance format use by Archi and are not meant to be looked at by users (and of course can change at anytime)

> We will work further on Specializations (and Profiles).

To be more precise, our goal is to support ArchiMate language customization as define in the standard specification. This being a huge work, we first focused on Specialization Profiles so that people can define their own concept types. The next step is to support generic profiles (ie. named set of properties). At this step, it will make sense to also add a documentation attribute so that people can describe the intended use of their profiles.





> Could specialisations be just special elements that do not have a graphical representation and as a consequence no 'Appearance' in the 'Properties' pane where all the other aspects of them could be edited? They could have their own folder below 'Relations' in the Model pane

That's now what a Profile is (per the specifications)

**Comment by heikkil** [comment]
Thanks for taking time to explain these things!

**Comment by jbsarrodie** [comment]
>That's now what a Profile is (per the specifications)

Sorry, should be read as: That's **not*** what a Profile is (per the specifications)
