### ISSUE TITLE
[feature request] Increase the size of bending points

### ISSUE THREAD

**Issue by MkCons** [archimatetool/archi#825]
Hi,

Is there a way to increase the size of the bending points? 

Even though I know they are supposed to be in the middle, it's really hard to find them. 

Thanks,

**Comment by Phillipus** [comment]
Yes, they are a bit small.

If you'd asked this a year ago I would have said that it's not possible because the bend-point sizes are internal to the Graphical Eclipse Framework (GEF) that Archi uses. But since we forked the GEF code we can modify this type of thing.

There are two types of bend-point - "Create" and "Move".  "Create" bend-points are smaller than "Move" bend-points and the single "Create" bend-point on a connection without any bend-points is not very visible. I think increasing the size of the "Create" bend-point by 1 pixel will help.

**Comment by MkCons** [comment]
Thank you for the tip. I increased the DEFAULT_HANDLE_SIZE in SquareHandle instead. That's even better, it's like an accessibility mode.

**Comment by Phillipus** [comment]
> Thank you for the tip. I increased the DEFAULT_HANDLE_SIZE in SquareHandle instead. That's even better, it's like an accessibility mode.

`DEFAULT_HANDLE_SIZE` affects all connection handles. But that's a matter of taste. For the next version of Archi, only the Create handle will be made bigger.

**Comment by MkCons** [comment]
I ended up creating a new menu in preferences to update the handle_size. If you think there's value I'll do a pull req but I don't I did a clean job: I store the value in swtPrefs (AppearancePreferencePage), plus set it in SquareHandle as a static value and then initialize when opening through ArchiWorkbenchWindowAdvisor.postWindowOpen.

**Comment by Phillipus** [comment]
I don't want to make drastic changes, so I'll just increase the Create bend-point size.
