### ISSUE TITLE
Missing aggregation relation between Communication Network and Node

### ISSUE THREAD

**Issue by davidsara** [archimatetool/archi#894]
### Version of Archi
5.0 beta2

### Operating System
Windows 11

### Expected Behaviour
It is possible to aggregate Nodes under Communication network as mentioned in Archimate 3.2 specification:

`It (communication network) can aggregate devices and system software to model the routers, switches, and firewalls that are part of the network infrastructure.`

### Actual Behaviour
Aggregation relationship is not offered when using Magic Connector and is rejected when using Aggregation relationship directly.

![image](https://user-images.githubusercontent.com/20066733/212085320-a9395a94-9233-42d1-9ae3-eb1e6f09c7fd.png)

### Steps to Reproduce the Behaviour
1. Create a new file
2. Place Communication Network and Node elements to the Default View
3. Try to set aggregation relationship between Communication Network and Node

When you will be updating Archimate Relationships under Help menu, you can also update the description to Archimate 3.2.

![image](https://user-images.githubusercontent.com/20066733/212085628-09fdf624-e835-4a17-bcd2-f56d13ffcece.png)

Regards,
David

**Comment by davidsara** [comment]
But maybe as in Archimate 3.2 device is no longer specialization of node, so you are correct and this is not bug 😄

**Comment by Phillipus** [comment]
@jbsarrodie Will be able to explain this.

> you can also update the description to Archimate 3.2.

Good catch, I'll do that. Thanks!

**Comment by jbsarrodie** [comment]
> But maybe as in Archimate 3.2 device is no longer specialization of node you are correct and this is not bug 😄 

Exactly, this aggregation has been removed from the specification (see appendix B for detailed list of allowed relationships).

In fact, what most people didn't notice since ArchiMate 3.0 is that Node is a highly abstract active structure which can be "IT" or "physical", so a Communication Network which is "IT" by nature cannot aggregate something which _could_ be "physical". OTOH, Distribution Network can aggregate both as Facility can aggregate Node, and Equipment can aggregate Device and System Software.

**Comment by davidsara** [comment]
Thank you very much for the great explanation!
