### ISSUE TITLE
[Feature Request] SVG support for object images

### ISSUE THREAD

**Issue by Yame12** [archimatetool/archi#933]
Hi, is it possible to add also support for vector based images like SVG for objects? Depending on the resolution of rasterized images and zoom level, it's starting to get blurry. Also using alternative icons for objects always looks a bit messy compared to the original icons.

Thanks,
Enrico

**Comment by Phillipus** [comment]
Sorry, SVG is not possible because of the way the Eclipse SWT framework works. It can only render raster graphics or draw primitive objects like lines and circles

I have seen an Eclipse implementation (GMF) that seems to support the SVG format but all that it is doing is converting, via Batik, the SVG file to a raster format.

**Comment by Yame12** [comment]
I see. SVG conversion would at least help so that we don't have to maintain our image/logo library with different file formats. But that might be a very specific issue for us only. 

Anyway, if it is currently not possible this feature request can be closed.
