### ISSUE TITLE
Shift + Delete Condition before performing action

### ISSUE THREAD

**Issue by nikolay-kochubashev** [archimatetool/archi#960]
Hi there!

In recent versions of Archi, it has become possible to remove an element from the model via Shift + Delete (Windows). This hotkey is used for the cut in text operation to the Windows clipboard.
I suggest that if the element is being renamed with the Shift + Delete key combination, cut the text into the buffer with the standard Windows capabilities, instead of deleting the Archimate element.

**Comment by Phillipus** [comment]
Hi, thanks for your report.

It seems that the Shift-Del key binding to delete objects from the model conflicts with the same key binding to cut text.

You can use Ctrl-X to cut text instead of Shift-Del, or you can edit the key bindings in Archi's Preferences and set a different key binding (like Ctrl-Del).

**Comment by nikolay-kochubashev** [comment]
Hi, Phillipus!
Thank you a LOT!
It's very convenient solution.

**Comment by Phillipus** [comment]
Good to hear that. I'll close this one.
